In [1]:
import numpy as np
import matplotlib.pylab as plt
%matplotlib inline

In [2]:
def objective(X):
    return np.trace(X.T.dot(X))
def gradient_objective(X):
    return 2*X

In [10]:
#Bregman Optimization
iter = 1000
dimension = 3
initial =np.arange(dimension**2).reshape((dimension,dimension))
B =np.zeros(shape=(dimension,dimension))
p =initial

for i in range(iter):
    initial = (p-B)/2.0
    y_k = initial+B
    u,d,v = np.linalg.svd(y_k.T,full_matrices=True)
    p=u.dot(np.eye(N=u.shape[1],M=v.shape[0])).dot(v)
    if not np.allclose(np.dot(p.T,p), np.identity(n=p.T.shape[0])):
        print "COnstrained optimization failed"
        break
#     print p
    B = B+initial-p

print (initial.T.dot(initial).astype(int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
print y_k 
u,d,v = np.linalg.svd(y_k,full_matrices=True)
print u.dot(np.diag(d)).dot(v)

[[  644.68506048  1000.33333333  1354.98160619]
 [ 3000.33333334  3741.39264248  4484.45195162]
 [ 5354.98160618  6484.45195162  7612.92229705]]
[[  644.68506048  1000.33333333  1354.98160619]
 [ 3000.33333334  3741.39264248  4484.45195162]
 [ 5354.98160618  6484.45195162  7612.92229705]]


In [5]:
from scipy import linalg
y=np.arange(12).reshape(4,3)
u,d,v = np.linalg.svd(y,full_matrices=False)
print v.shape
p=u.dot(np.eye(N=u.shape[1],M=v.shape[0])).dot(v)


print np.allclose(np.dot(p.T,p), np.identity(n=p.T.shape[0]))

(3, 3)
True


In [ ]:
y=np.arange(12).reshape(4,3)
def objective(X):
    X=X.reshape(4,3)
    return np.trace(X.T.dot(X))+np.trace((X-y).T.dot(X-y))
def derivative_analytic(X):
    X=X.reshape(4,3)
    
    return ( 4*X-2*y).flatten()

from scipy.misc import derivative
times = 100
numeric_gradient=[]
analytic_gradient=[]
grad=[]
for i in range(times):
    tmp=np.random.rand(12)
    res=derivative(objective,tmp)
    
    grad.append(np.linalg.norm(res-derivative_analytic(tmp)))
                            
plt.plot(grad,label='diffgrad')
plt.legend()

from scipy.optimize import minimize
q0= y/4.0

iter=0
while True:
    q1= minimize(fun=objective,x0=np.random.rand(3*4),method='CG',jac=derivative_analytic).x
    q2= minimize(fun=objective,x0=np.random.rand(3*4),method='CG').x
    if  np.allclose(objective(q1),objective(q0)):
        print 'closed form','\n',q0.reshape(3,4),'\n'
        
        print 'Using analytical derivative','\n',q1.reshape(3,4),'\n'
        print 'Numerical','\n',q2.reshape(3,4),'\n'
        print objective(q) 
        print objective(q1)
        print objective(q2)

        break;

In [8]:
from scipy.optimize import minimize
dimension = 3
initial =np.arange(dimension**2).reshape((dimension,dimension))
B =np.zeros(shape=(dimension,dimension))
p =initial

def objective2(X,y):
    X=X.reshape(dimension,dimension)
    
    return np.trace(X.T.dot(X))+np.trace((X-y).T.dot(X-y))
def objective2_grad(X,y):
    X=X.reshape(dimension,dimension)
    return ( 4*X-2*y).flatten()
    
iter =1000
for ind in range(iter):
    #initial = (B-p)/4.0
    initial= minimize(fun=objective2,x0=initial,method='CG',args=(B-p)).x.reshape(dimension,dimension)
#     print  np.allclose(objective(q.x),objective(q1))
    y_k = initial+B
    u,d,v = np.linalg.svd(y_k.T,full_matrices=True)
    p=u.dot(np.eye(N=u.shape[1],M=v.shape[0])).dot(v)
    if not np.allclose(p.T.dot(p),np.identity(p.shape[1])):
                       print 'asghar'
    if not np.allclose(np.dot(p.T,p), np.identity(n=p.T.shape[0])):
        print "Constrained optimization failed"
        break
#     print p
    B = B+initial-p

print (initial.T.dot(initial).astype(int))

[[859927983529972864  21551185877235588  14116410738997902]
 [ 21551185877235588   4305017314023172   4619475238468281]
 [ 14116410738997902   4619475238468281   8364614950365170]]


In [275]:
np.random.rand(12)

array([ 0.21015905,  0.46283729,  0.42733062,  0.73396545,  0.24949484,
        0.07823205,  0.17451367,  0.96115526,  0.80865103,  0.68216103,
        0.43624442,  0.60937541])

In [276]:
np.linalg.norm(y)**2,np.trace(y.T.dot(y))

(10.267122366795929, 10.267122366795927)

In [24]:
import numpy as np
iter = 100
dimension = 3 # assume H is 3*3 so the optimal value should be 3

#initialization based on the sketch of algorithm
H =np.arange(dimension**2).reshape((dimension,dimension)) #This is just initial value of H
H = np.random.randn(dimension,dimension)
P =H 
B =np.zeros(shape=(dimension,dimension))
r=2


for i in range(iter):
    H = (P-B)*(r/(2.0+r))
    y_k = H+B
    u,d,v = np.linalg.svd(y_k,full_matrices=True)
    
    P=u.dot(np.eye(N=u.shape[1],M=v.shape[0])).dot(v)
    if  not np.allclose(np.dot(P.T,P), np.identity(n=P.T.shape[0])):
        print "Constrained subproblem failed"
        break

    B = B+H-P

print "Is an orthogonal constraint statisifed? Is the printed matrix equal to I?",'\n'
print (H.T.dot(H))
print "objective is ",np.trace(H.T.dot(H)) ,np.trace(H.T.dot(H))==H.T.shape[0]

Is an orthogonal constraint statisifed? Is the printed matrix equal to I? 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
objective is  3.0 True
