# Confirmation of working idea of bregman to handle symmetric constraint
Here, I am trying ti solve a very simple feasibility problem to check idea of writing symmetric constratin as linear to fit it in the framework of bregman works or not.
Let's solve following optimization:
 $$min \quad 1$$
 $$s.t \quad A^T=A$$
In order to solve that we need to write down the above constraint as a linear operator and a vector something like $$Dx=f$$.We can easily do that by vectorizing A and writing operator D as a swapping operator. I show it on the code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.sparse as sp


In [5]:
from scipy.sparse import csr_matrix,csc_matrix

dimension=3
A = np.random.randint(low=0,high=99,size=(dimension,dimension))
M=np.zeros((dimension**2,dimension**2))
# print row_
row_=np.arange(0,dimension**2).reshape(dimension,dimension)
col = np.arange(0,dimension**2).reshape(dimension,dimension,order='F')
ij=np.vstack((row_.flatten(),col.flatten()))

# indptr = row_.flatten()
# indices=col.flatten()
data=np.ones(dimension**2)
q_sparse=csr_matrix( (data,ij), shape=(dimension**2,dimension**2) )
# csr_matrix((data,ij))
AT=csr_matrix(A.flatten()).dot(q_sparse)
# print np.allclose(q_sparse,M)
q=np.dstack((row_,col))

for i in range(dimension):
    M[q[i,:,0],q[i,:,1]]=1
res= M.dot(A.flatten()).reshape(dimension,dimension)
# print np.allclose(M,q_sparse)
print type(AT)
print np.allclose(AT.todense(),A.T.flatten())

<class 'scipy.sparse.csr.csr_matrix'>
True


In [7]:


iter=100
r=2
b=np.random.randint(low=0,high=99,size=dimension**2)
print b.shape
D=M-np.identity(dimension**2)
print D.shape
for i in range(iter):
#     x=sp.linalg.spsolve(D.T.dot(D),D.T.dot(b))
    x=np.linalg.lstsq(-1*D.T.dot(D),D.T.dot(b))[0]
#     print x
    b=b+D.dot(x)

print x
x=x.reshape(dimension,dimension)
print np.allclose(x,x.T)

(9,)
(9, 9)
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
True


In [54]:

sp.linalg.li

<module 'scipy.sparse.linalg' from '/home/mohammad/anaconda2/lib/python2.7/site-packages/scipy/sparse/linalg/__init__.pyc'>

In [8]:
print M



[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [81]:
M.dot(A.flatten())-A.flatten()

array([ 59.,  26.,  92.,  19.,   9.,  74.,   6.,  77.,   7.])

In [83]:
A.flatten(order='F')

array([59, 26, 92, 19,  9, 74,  6, 77,  7])

In [84]:
A

array([[59, 19,  6],
       [26,  9, 77],
       [92, 74,  7]])